---
services:
  perfect-homelab:
    container_name: perfect-homelab
    build: .
    restart: unless-stopped
    ports:
      - 8089:8000
    volumes:
      - ./:/docs
    environment:
      TZ:  Europe/Paris
    networks:
      - material-mkdocs

# CREATION DU NETWORK material-mkdocs :
# docker network create --driver=bridge --subnet=172.20.0.0/16 --gateway=172.20.0.1 material-mkdocs
networks:
  material-mkdocs:
    external: true

# networks:
#   material-mkdocs:
#     name: material-mkdocs
#     driver: bridge
#     ipam:
#       config:
#         - subnet: "172.20.0.0/16"
#           gateway: "172.20.0.1"