---
version: "3.9"
services:
  perfect-homelab:
    container_name: perfect-homelab
    build: .
    restart: unless-stopped
    ports:
      - 8089:8000
    volumes:
      - ./:/docs
    environment:
      TZ:  Europe/Paris
    networks:
      - mkdocs

networks:
  mkdocs:
    name: mkdocs
    driver: bridge
    ipam:
      config:
        - subnet: "172.24.0.0/16"
          gateway: "172.24.0.1"